### ISSUE TITLE
Name should be optional parameter

### ISSUE THREAD

**Issue by tamtakoe** [kaminaly/gulp-sync#4]
If I run `t1` and `t2`

<pre>gulp.task('t1', gulpsync.sync(['a', 'b', 'c']));
gulp.task('t2', gulpsync.sync(['d', 'e', 'f']));</pre>

`d`, `e`, `f` only will be run.

I need name tasks

<pre>gulp.task('t1', gulpsync.sync(['a', 'b', 'c'], 'sync t1'));
gulp.task('t2', gulpsync.sync(['d', 'e', 'f'], 'sync t2'));</pre>

It uncomfortable. Name should be optional parameter

**Comment by kaminaly** [comment]
Thank you for advice.
It was fixed!
