### ISSUE TITLE
Pass parameters into tasks

### ISSUE THREAD

**Issue by doronsever** [kaminaly/gulp-sync#6]
Is there a way to pass params into the task?
For instance 

  gulp.task('default', gulpsync.sync(['a --platform desktop', 'b', 'c']))

**Comment by kaminaly** [comment]
It can't pass params into the task.
But if you prepare tasks of all necessary types, you can use it as a simple conditional.

For example

```
gulp.task('a:desktop', function(){
    // for desktop
});
gulp.task('a:mobile', function(){
    // for mobile
});

gulp.task('default', gulpsync.sync(['a:desktop', 'b', 'c']));
```

**Comment by doronsever** [comment]
Well, i figured it out that when you run `gulp [taskname] --env dektop` the env parameter will pass through to all subtasks.
10x alot though!

**Comment by kaminaly** [comment]
oh, It's very simple solve!
